version: "3.8"

services:
    api:
        build: ./app
        ports: 
            - 8080:8080

        volumes:
            - ./app:/app
        restart: always
        depends_on:
            - db

    db:
        image: postgres:13.0-alpine
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        ports: 
            - 5432:5432
        env_file:
        - ./app/.env
    front_app:
        build: ../../Front_END/Scientific-Articles-Search-Web-App/front_app
        ports:
            - '3000:3000'
        restart: always
        

        
        
volumes:
    postgres_data:
    static_volume:
    media_volume: