version: "3.8"

services:
    api:
        build: ./app
        ports: 
            - 8080:8080

        volumes:
            - ./app:/app
        restart: always
        depends_on:
            - db

    db:
        image: postgres:13.0-alpine
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        ports: 
            - 5432:5432
        env_file:
        - ./app/.env
    front_app:
        build: ../../Front_END/Scientific-Articles-Search-Web-App/
        ports:
            - '3000:3000'
        restart: always
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
        container_name: my-elasticsearch
        environment:
        - discovery.type=single-node
        ports:
        - '9200:9200'
        - '9300:9300'

    kibana:
        image: docker.elastic.co/kibana/kibana:7.15.1
        container_name: my-kibana
        ports:
        - "5601:5601"
        environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        depends_on:
        - elasticsearch   

        
        
volumes:
    postgres_data:
    static_volume:
    media_volume: